"""Change model

Revision ID: ee9d6dbaf282
Revises: 0eb8d947e4c2
Create Date: 2020-09-14 20:46:49.812194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee9d6dbaf282'
down_revision = '0eb8d947e4c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_nickname_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_nickname_key', 'user', ['nickname'])
    # ### end Alembic commands ###
